In [7]:
#check numpy version
import numpy as np
np.__version__

'1.22.1'

In [9]:
#NUMPY INBUILT DOCUMENTATION
np?


In [10]:
np.array([1, 2, 3, 5, 7, 9])
#create array

array([1, 2, 3, 5, 7, 9])

In [11]:
np.array([range(i, i + 3) for i in [2, 4, 6]])
#initializing a multidimensional array using list of lists

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

#arrays from scratch


In [13]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3, 5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [25]:
#linear sequence
np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [22]:
#evenly spaced
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.random.randint(0, 10,(3, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [19]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.empty(3)

array([1.08346703e-311, 0.00000000e+000, 6.47591605e-319])

In [29]:
np.random.seed(0)
x1= np.random.randint(10, size=6)
x2= np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))