In [5]:
#trigonometric functions
#array of angles
import numpy as np
theta = np.linspace(0, np.pi, 3)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [6]:
#inverse  trigonometry
x = [-1, 0, 1]
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


In [7]:
#exponentials
x = [1, 2, 3]
print(np.exp(x))
print(np.exp2(x))
print(np.power(3, x))

[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3  9 27]


In [8]:
#logarithms
x = [1, 2, 4, 10]
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[0.         0.69314718 1.38629436 2.30258509]
[0.         1.         2.         3.32192809]
[0.         0.30103    0.60205999 1.        ]


In [9]:
#special ufuncs
from scipy import special
x = [1, 5, 10]
print(special.gamma(x))
print(special.gammaln(x))
print(special.beta(x, 2))

ModuleNotFoundError: No module named 'scipy'